package com.gigaspaces.webuitf.datagrid.transactionspanel;

/**
 * Created by evgenyf on 11/19/2015.
 */
public interface SpaceTransactionsConstants {
    String TRANSACTIONS_GRID = "gs-slider-grid-TRANSACTIONS_LIST";
    String TYPES_GRID_ID = "gs-slider-grid-TRANSACTION_LOCKED_OBJECTS_LIST";

    int WAIT_TIMEOUT_IN_MS = 5000;

    String TD_CLASS_NAME_PREFIX = "x-grid3-td-";
    String COL_CLASS_NAME_PREFIX = "x-grid3-col-";

    String TRANSACTION_ID = "transaction_id";
    String TRANSACTION_TYPE = "transaction_type";
    String TRANSACTION_START_TIME = "transaction_start_time";
    String TRANSACTION_END_TIME = "transaction_end_time";
    String TRANSACTION_STATUS = "transaction_status";
    String TRANSACTION_NUM_OF_LOCKED_OBJECTS = "transaction_num_of_locked_objects";

    String TD_TRANSACTION_ID_CLASS = TD_CLASS_NAME_PREFIX + TRANSACTION_ID;
    String TD_TRANSACTION_TYPE_CLASS = TD_CLASS_NAME_PREFIX + TRANSACTION_TYPE;
    String TD_TRANSACTION_START_TIME_CLASS = TD_CLASS_NAME_PREFIX + TRANSACTION_START_TIME;
    String TD_TRANSACTION_END_TIME_CLASS = TD_CLASS_NAME_PREFIX + TRANSACTION_END_TIME;
    String TD_TRANSACTION_STATUS_CLASS = TD_CLASS_NAME_PREFIX + TRANSACTION_STATUS;
    String TD_TRANSACTION_NUM_OF_LOCKED_OBJECTS_CLASS = TD_CLASS_NAME_PREFIX + TRANSACTION_NUM_OF_LOCKED_OBJECTS;

    String COL_TRANSACTION_ID_CLASS = COL_CLASS_NAME_PREFIX + TRANSACTION_ID;
    String COL_TRANSACTION_TYPE_CLASS = COL_CLASS_NAME_PREFIX + TRANSACTION_TYPE;
    String COL_TRANSACTION_START_TIME_CLASS = COL_CLASS_NAME_PREFIX + TRANSACTION_START_TIME;
    String COL_TRANSACTION_END_TIME_CLASS = COL_CLASS_NAME_PREFIX + TRANSACTION_END_TIME;
    String COL_TRANSACTION_STATUS_CLASS = COL_CLASS_NAME_PREFIX + TRANSACTION_STATUS;
    String COL_TRANSACTION_NUM_OF_LOCKED_OBJECTS_CLASS = COL_CLASS_NAME_PREFIX + TRANSACTION_NUM_OF_LOCKED_OBJECTS;
}
